#!/bin/sh

# check if vim or vim-tiny is installed
if [ -z "$(command -v vim)" -o -z "$(command -v vimtutor)" ]; then
  echo "Warning, doesn't look like you have full Vim version."
fi

# check if neovim is installed
if [ -z "$(command -v nvim)" ] ; then
  echo "neovim not found"
fi

# yes, rm -rf is not advised here but I'm blowing these whole dirs away for my stuff anyway
rm -rf "$HOME/.vim/"
rm -rf "$HOME/.vimrc"
rm -rf "$HOME/.config/nvim/"
mkdir -p "$HOME/.config/nvim/"
mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
ln -sf "$PWD/init.lua" "$HOME/.config/nvim/init.lua"
