" ======================================= BEGIN CONFIG =============================================

" checks for vim-tiny (vi)
if has("eval")
        let skip_defaults_vim = 1
endif

" ======================================= basic tweaks =============================================
set nocompatible
set autoindent
set autowrite
set ruler
set showmode
set tabstop=4
set vb t_vb=""
set softtabstop=4
set shiftwidth=4
set smartindent
set smarttab
set noignorecase
set noerrorbells
set visualbell
set cursorline
" ==================================================================================================


" ============================== misc stuff, makes vim less annoying ===============================
if v:version >=  800
    set nofixendofline
    set listchars=space:*,trail:*,nbsp:*,extends:>,precedes:<,tab:\|>
    set listchars+=eol:↩
    set foldmethod=manual
    set nofoldenable
endif

match Visual '\s\+$'

if has('termguicolors')
    set termguicolors
endif
set t_Co=256
" ==================================================================================================


" ====================================== more misc stuff ===========================================
set textwidth=100           " this is more modern, might think it's stupid later and change my mind
set colorcolumn=101                                             " already leaning toward stupid tbh
set spc=
set expandtab
set nobackup                                                    " because I like living on the edge
set noswapfile                                                     " and having cleaner directories
set nowritebackup
set noundofile
set icon
set hlsearch
set incsearch
set linebreak
set wrapscan
set nowrap
set shortmess=aoOtTI
set viminfo='20,<1000,s1000                                 " prevent truncated yanks, deletes, etc
set ttyfast
set ttimeoutlen=0
set showmatch
filetype plugin indent on
set wildmenu
set omnifunc=syntaxcomplete#Complete
set noshowmatch
set hidden
set cinoptions+=:0
set history=100
" ==================================================================================================


if has("eval")
        let g:loaded_matchparen=1
endif

" format shell on save
if has("eval") " vim-tiny detection
" TODO check for shfmt and shellcheck before defining
" FIXME stop from blowing away file when there is shell error
fun! s:FormatShell()
    let l:pos = getcurpos()
    "silent execute '%!shfmt' " FIXME: bug report to shfmt
    call setpos('.', l:pos)
endfun
autocmd FileType sh autocmd BufWritePre <buffer> call s:FormatShell()
endif

fun! JumpToDef()
    if exists("*GotoDefinition_" . &filetype)
        call GotoDefinition_{&filetype}()
    else
    exe "norm! \<C-]>"
    endif
endf


" ===================================== statusline =================================================
set laststatus=0
set ruf=%30(%=%#LineNr#%.50F\ [%{strlen(&ft)?&ft:'none'}]\ %l:%c\ %p%%%)
" ==================================================================================================


" =========================================== netrw ================================================
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize=25
" ==================================================================================================

nnoremap confe :e $HOME/.vimrc<CR>
nnoremap confr :source $HOME/.vimrc<CR>
nnoremap coming i_In development..._<Esc>

let mapleader=" "
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>e :Explore<CR>
nnoremap <leader>pv :Vexplore<CR>
nnoremap <leader>pl :Lexplore<CR>
nnoremap <leader>r :set number! relativenumber!<CR>



""""""""""""""""""""
"     Vim-Plug      "
"""""""""""""""""""""
" as a rule-of-thumb, I prefer built-in functions and filters over extensions
" only runs if vim-plug script is found in ~/.vim/autoload/
if filereadable(expand("~/.vim/autoload/plug.vim"))

    call plug#begin('~/.local/share/vim/plugins')

        Plug 'conradirwin/vim-bracketed-paste'
        Plug 'jiangmiao/auto-pairs'
        Plug 'vim-pandoc/vim-pandoc'
        Plug 'rwxrob/vim-pandoc-syntax-simple'
        Plug 'dense-analysis/ale'
        Plug 'fatih/vim-go'

        " coc requires nvim 0.8
        if has('nvim-0.8')
            Plug 'neoclide/coc.nvim', {'branch': 'release'}
        endif

        " treesitter rewrite requires nvim 0.11
        if has('nvim-0.11')
            Plug 'nvim-treesitter/nvim-treesitter'
            Plug 'rwxrob/nvim-treesitter-textobjects', {'do': ':TSUpdate'}
        endif

        if has('nvim')
            Plug 'xolox/vim-misc'
            Plug 'xolox/vim-lua-ftplugin'
        endif

  call plug#end()

        fun! JumpToDef()
            if exists("*GotoDefinition_" . &filetype)
                call GotoDefinition_{&filetype}()
            else
                exe "norm! \<C-]>"
            endif
        endf

        set signcolumn=yes
        let g:ale_set_signs = 1
        let g:ale_sign_info = '✨'
        let g:ale_sign_error = '🔥'
        let g:ale_sign_warning = '❗️'
         let g:ale_sign_hint = '💡'

        let g:ale_linters = {
            \'go': ['gometalinter', 'gofmt', 'gobuild'],
            \'perl': ['perl', 'perlcritic'],
            \'python': ['ruff'],
            \'proto': ['protolint'],
            \}
        let g:ale_linter_aliases = {'bash': 'sh'}
        let g:ale_perl_perlcritic_options = '--severity 3'

        let g:ale_fixers = {
            \'sh': ['shfmt'],
            \'bash': ['shfmt'],
            \'perl': ['perltidy'],
            \'python': ['black'],
            \'proto': ['protolint'],
            \}
        let g:ale_fix_on_save = 1
        let g:ale_perl_perltidy_options = '-b'

        let g:pandoc#formatting#mode = 'h' " A'
        let g:pandoc#formatting#textwidth = 72

        " golang
        let g:go_fmt_fail_silently = 0
        "let g:go_fmt_options = '-s'
        let g:go_fmt_command = 'goimports'
        let g:go_fmt_autosave = 1
        let g:go_gopls_enabled = 1
        let g:go_highlight_types = 1
        let g:go_highlight_fields = 1
        let g:go_highlight_functions = 1
        let g:go_highlight_function_calls = 1
        let g:go_highlight_operators = 1
        let g:go_highlight_extra_types = 1
        let g:go_highlight_variable_declarations = 1
        let g:go_highlight_variable_assignments = 1
        let g:go_highlight_build_constraints = 1
        let g:go_highlight_diagnostic_errors = 1
        let g:go_highlight_diagnostic_warnings = 1
        let g:go_code_completion_enabled = 1
        let g:go_auto_sameids = 0
        set updatetime=100

        " common go macros
        au FileType go nmap <leader>m ilog.Print("made")<CR><ESC>
        au FileType go nmap <leader>n iif err != nil {return err}<CR><ESC>

    endif

" colorscheme tweakz
if has("syntax")
    syntax on
    set background=dark
    colorscheme selenized
    hi clear SignColumn
    hi Comment ctermbg=NONE guibg=NONE gui=italic cterm=italic
    hi LineNr cterm=NONE ctermbg=NONE gui=NONE guibg=NONE
    hi Normal ctermbg=NONE guibg=NONE
    hi StatusLine ctermfg=11 guifg=#ebc13d
endif

" ====================================== END CONFIG ================================================
