# my window manager config ;)
set -sg escape-time 0
unbind C-a
unbind C-b
set-option -g prefix C-a
bind -r y setw synchronize-panes
set -g renumber-windows on
# form vim/tmux d/y buffer sync
set -g focus-events
#bind-key C-a last-window
unbind =
bind = split-window -h -c "#{pane_current_path}"
unbind -
bind - split-window -v -c "#{pane_current_path}"

# vi for copy mode
setw -g mode-keys vi

# vi for command status
set -g status-keys vi

# vi keys to resize
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# vi keys to select panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind f run-shell "tmux new ~/Scripts/tmux-session-dispensary.sh"
bind E show-environment -g

# key binds for dev session
bind b send-keys -t 2 "make" C-m
bind R send-keys -t 2 "make run" C-m
bind t send-keys -t 3 "make test" C-m
bind g send-keys -t 3 "gdb ./a.out" C-m
bind C send-keys -t 2 "clear" C-m

# avoid cursor movement messing with resize
set -g repeat-time 202

# Improve terminal colors
#set -a terminal-features "xterm-256color"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",wezterm:RGB"

set -g status off # starting to doubt the usefulness of the status bar, just use root+i

set -g base-index 1
setw -g pane-base-index 1
# pane borders
set -g pane-border-style "fg=colour0"
set -g pane-active-border-style "fg=colour10"

# message styling
set -g message-style "bg=colour196,fg=colour232"
set -g message-command-style "bg=colour1,fg=colour232"

# reload config
bind -r r source-file ~/.tmux.conf

set -g automatic-rename
set -g allow-passthrough on
